[tool.poetry]
name = "shared"
version = "0.1.0"
description = "Shared Python code for the osint project"
authors = ["Ishay Sela <ishaisela@email.com>"]
packages = [{ include = "shared" }]

[tool.poetry.dependencies]
python = ">=3.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"