FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY /shared/python /app/services/shared/python
RUN pip install -e /app/services/shared/python
COPY /ingestion/telegram-scraper/requirements.txt .
RUN pip install --no-cache-dir -r /app/requirements.txt watchdog

COPY /ingestion/telegram-scraper .

CMD ["watchmedo", "auto-restart", "--pattern=*.py", "--recursive", "--", "python", "app.py"]
