name: deploy-app

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: $${{secrets.TS_OAUTH_CLIENT_ID}}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ishay-osint-cd

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEPLOY_USERNAME }}
          password: ${{ secrets.SSH_DEPLOY_PASSWORD }}
          envs: GITHUB_TOKEN
          script: |
            echo "Starting deployment process"
            mkdir -p ~/app
            cd ~/app
            if [ -d ".git" ]; then
                git -c "url.https://x-access-token:${GITHUB_TOKEN}@github.com/.insteadOf=https://github.com/" \
                -C ~/app fetch origin master \
                && git -C ~/app reset --hard origin/master
            else
              git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/IshaySela/israel-osint-ai.git" ~/app
            fi
            docker compose down
            docker compose up --build -d
            echo "Finished deployment process"